
# Permet dâ€™utiliser pip install plus proprement.

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# inclure l'excel
[tool.setuptools.package-data]
"packageGES" = ["data/*.xlsx"]